deployment:
  tasks:
    - export DEPLOYPATH=/home/murree125/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH
    - /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan optimize:clear
