deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html
    # Copy all files except .git to public_html
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH/.env
    # Install composer dependencies
    - cd $DEPLOYPATH && composer install --no-dev --optimize-autoloader
    # Run migrations
    - cd $DEPLOYPATH && php artisan migrate --force
    # Clear caches
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
