deployment:
  tasks:
    - export DEPLOYPATH=/locumkit.murreefoods.com
    # Copy all files from repo to document root
    - /bin/cp -R * $DEPLOYPATH
    # Copy .env separately
    - /bin/cp -R .env $DEPLOYPATH/.env
    # Composer install
    - cd $DEPLOYPATH && composer install --no-dev --optimize-autoloader
    # Laravel migrations
    - cd $DEPLOYPATH && php artisan migrate --force
    # Cache configs
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
